version: '3.4'
services:
  testTrello:
    # repo https://github.com/grihabor/pytest.images
    image: grihabor/pytest:python3.7-alpine
    working_dir: /usr/src/
    volumes:
      - $PWD:/usr/src/
      - $PWD/testTrello-data:/root/
    command: pytest .
